# Generated by Django 2.1.7 on 2019-02-21 13:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import monologue_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_saids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='action',
            field=models.ForeignKey(default=monologue_api.models.get_default_action, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='accounts', to='monologue_api.Action', verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, max_length=150, verbose_name='プロフィール'),
        ),
        migrations.AlterField(
            model_name='account',
            name='emotion',
            field=models.ForeignKey(blank=True, default=monologue_api.models.get_default_emotion, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='accounts', to='monologue_api.Emotion', verbose_name='emotion'),
        ),
        migrations.AlterField(
            model_name='account',
            name='following_accounts',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='following accounts'),
        ),
        migrations.AlterField(
            model_name='account',
            name='origin',
            field=models.ImageField(default='static/photos/fish_jellyfish.png', upload_to='static/photos', verbose_name='origin of an icon image'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': 'そのアカウントIDを持ったアカウントはすでに存在しています'}, help_text='Required. 31 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=31, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='アカウントID'),
        ),
    ]
