# Generated by Django 2.1.5 on 2019-02-08 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import monologue_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='no action', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(default='no emotion', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Said',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=140)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.ForeignKey(default=monologue_api.models.get_default_action, on_delete=django.db.models.deletion.CASCADE, related_name='saids', to='monologue_api.Action')),
                ('emotion', models.ForeignKey(default=monologue_api.models.get_default_emotion, on_delete=django.db.models.deletion.CASCADE, related_name='saids', to='monologue_api.Emotion')),
            ],
        ),
    ]
