# Generated by Django 2.1.7 on 2019-02-21 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import monologue_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('monologue_api', '0002_said_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(default='no action', max_length=31, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='emotion',
            field=models.CharField(default='no emotion', max_length=31, verbose_name='emotion'),
        ),
        migrations.AlterField(
            model_name='said',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saids', to=settings.AUTH_USER_MODEL, verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='said',
            name='action',
            field=models.ForeignKey(default=monologue_api.models.get_default_action, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='saids', to='monologue_api.Action', verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='said',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='said',
            name='emotion',
            field=models.ForeignKey(default=monologue_api.models.get_default_emotion, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='saids', to='monologue_api.Emotion', verbose_name='emotion'),
        ),
        migrations.AlterField(
            model_name='said',
            name='text',
            field=models.TextField(max_length=140, verbose_name='本文'),
        ),
    ]
